spring:
  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true
          routes:
            - id: auth_route
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/login,/api/v1/forgot-password/verify,/api/v1/forgot-password/send-otp
              filters:
                - name: CircuitBreaker
                  args:
                    name: authCB
                    fallbackUri: forward:/fallback/circuit-breaker/auths
            - id: user_route_not_authentication
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/sign-up,/api/v1/users/forgot-password/send-otp,/api/v1/users/forgot-password/otp/verify
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCB
                    fallbackUri: forward:/fallback/circuit-breaker/users
            - id: user_route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCB
                    fallbackUri: forward:/fallback/circuit-breaker/users
                - name: Authentication
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
          httpclient:
            response-timeout: 15s
resilience4j:
  circuitbreaker:
    configs:
      defaultConfig:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 30
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      authCB:
        base-config: defaultConfig
      userDB:
        base-config: defaultConfig
management:
  health:
    mongodb:
      enabled: false
  endpoint:
    gateway:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG